//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Programing.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class language
    {
        public Nullable<int> Id { get; set; }
        public string language1 { get; set; }
        public string founder { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<bool> Ispopular { get; set; }
    }
}
